-- 코드를 작성해주세요
-- 1. 연도별로 분화된 가장 큰 대장균를 구한다.
# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE FROM ECOLI_DATA GROUP BY DIFFERENTIATION_DATE


-- 2. 연도별 가장 큰 대장균의 크기 - 각 대장균의 크기 구하기
SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR, B.MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA
LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B
ON YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV




